#
# Run pre-commit hooks. You can run them without installing
#  the hook with
#
# $ pre-commit run --all-files
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# Note: Use docker images with specific digests to ensure reproducibility and security.
default_stages:
  - pre-commit
  - manual
  - pre-push
# Override language hinting because we need mypy to use python3.12,
#   even if some hooks don't support it yet.
default_language_version:
  python: python3.12
repos:
#
# Python linters.
#
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.15.4
  hooks:
  # Run the linter.
  - id: ruff
    args: [--fix]
    exclude: \.ipynb$
  - # Run the formatter.
    id: ruff-format
    exclude: \.ipynb$

